# Generated by Django 3.2.5 on 2021-07-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_email', models.EmailField(max_length=254)),
                ('reporter_name', models.CharField(max_length=50)),
                ('reply_body', models.TextField()),
                ('reply_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
