# Generated by Django 3.2.5 on 2021-07-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='report_screenshot'),
        ),
    ]
